site_name: Enlace

theme:
  name: "material"
  palette:

  # Palette toggle for light mode
  - scheme: default
    # primary: green
    # accent: orange
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.footer

extra:
  generator: false

plugins:
  - mkdocstrings:
      handlers:
          python:
            options:
              show_if_no_docstring: false
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              show_object_full_path: false
              show_docstring_type_aliases: true
              backlinks: tree
              docstring_options:
                warn_missing_types: false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      default_lang: python
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
        title: On this page

# pygmentize -S colorful -f html > docs/stylesheets/test.css
# extra_css:
#   - stylesheets/test.css

nav:
  - index.md
  - Concepts:
    - concepts/install.md
    - concepts/first-steps.md
    - concepts/strategies.md
    - Applying Strategies:
      - concepts/applying-strategies/sequential-api.md
      - concepts/applying-strategies/dict-api.md
    - concepts/record-linkage.md
    - concepts/rules-api.md
    - concepts/boolean-operators.md
    - concepts/discrete-strategies.md
    - concepts/supported-backends.md
    - concepts/customizing-strategies.md
    - concepts/using-synthetic-data.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - reference/enlace.md
    - reference/rules.md
    - reference/custom.md
    - reference/datasets.md
  - explanation.md