site_name: Enlace

theme:
  name: "material"
  palette:

  # Palette toggle for light mode
  - scheme: default
    # primary: green
    # accent: orange
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins:
  - mkdocstrings:
      handlers:
          python:
            options:
              show_if_no_docstring: false
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              show_object_full_path: false
              show_docstring_type_aliases: true
              backlinks: tree
              docstring_options:
                warn_missing_types: false

markdown_extensions:
- pymdownx.highlight:
    default_lang: python

nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - reference/enlace.md
    - reference/rules.md
    - reference/custom.md
    - reference/datasets.md
  - explanation.md