site_name: Enlace

theme:
  name: "material"
  palette:

  # Palette toggle for light mode
  - scheme: default
    # primary: green
    # accent: orange
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  
  features:
    - content.code.copy
    # - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.tracking

extra:
  generator: false

plugins:
  - mkdocstrings:
      handlers:
          python:
            options:
              show_if_no_docstring: false
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              show_object_full_path: false
              show_docstring_type_aliases: true
              backlinks: tree
              docstring_options:
                warn_missing_types: false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      default_lang: python
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      title: On this page 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
  - index.md
  - Tutorials:
    - tutorials/install.md
    - tutorials/first-steps.md
    - tutorials/strategies.md
    - Applying Strategies:
      - tutorials/applying-strategies/sequential-api.md
      - tutorials/applying-strategies/dict-api.md
    - tutorials/record-linkage.md
    - Advanced Strategies:
      - tutorials/advanced-strategies/rules-api.md
      - tutorials/advanced-strategies/boolean-operators.md
      - tutorials/advanced-strategies/discrete-strategies.md
    - tutorials/supported-backends.md
    - tutorials/customizing-strategies.md
    - tutorials/using-synthetic-data.md
  - How-To Guides: 
    - how-tos/choose-the-right-api.md
    - how-tos/build-iterative-workloads.md
  - Explanation:
    - explanation/what-diff-in-apis.md
    - explanation/binary-vs-discrete.md
    - explanation/how-does-it-work.md
  - Reference:
    - reference/enlace.md
    - reference/rules.md
    - reference/custom.md
    - reference/datasets.md
