name: python | validation

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  linting:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v6

        - name: python | setup
          uses: actions/setup-python@v6
          with:
            python-version-file: "pyproject.toml"

        - name: uv | install
          uses: astral-sh/setup-uv@v7
          with:
            version: "0.10.4"

        - name: liken | project install
          run: |
            uv sync --locked --all-extras --group lint

        - name: Install Task
          uses: arduino/setup-task@v2
          with:
            version: 3.48.0

        - name: lint
          run: |
            task lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v6

      - name: python | setup  ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: uv | install
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.4"

      - name: liken | project install
        run: |
          uv sync --locked --all-extras --group test

      - name: tests | run
        run: |
          uv run coverage run -m pytest tests/ -v
          uv run coverage xml --omit "tests/**/*"
      
      - name: tests | coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coverage.xml"
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          # thresholds: "${{ inputs.low-pct-coverage-threshold }} ${{ inputs.high-pct-coverage-threshold }}"

      - name: coverage | add header
        run: |
          echo "## Coverage Report" > coverage.md
          cat code-coverage-results.md >> coverage.md
  
      - name: tests | pr-comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request'}}
        with:
          header: Coverage Report
          hide_and_recreate: true
          path: coverage.md