name: ⚙️ release | PyPI

on: 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write # mandatory for trusted publishing

jobs:
  build:
    name: Package | Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: python | setup
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: uv | install
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.4"

      - name: uv | build package wheel
        run: uv build
  

  publish-to-testpypi:
    name: Package | Publish to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/liken

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Publish to TestPyPI
        run: uv publish --publish-url https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Package | Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/') # only publish to PyPI with tags
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/liken

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Publish to PyPI
        run: uv publish

  docs:
    name: Docs
    needs:
      - publish-to-pypi
    uses: ./.github/workflows/docs.yml
    if: startsWith(github.ref, 'refs/tags/')